name: Update Links Workflow

on:
  # Allow manual triggering from the GitHub Actions UI
  workflow_dispatch:
  # Schedule to run at 2:00 AM every day (uncomment the cron line to activate)
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  test-and-update-links:
    runs-on: ubuntu-latest

    steps:
      # Step to set up the repository for the workflow
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to set up Python with the specified version
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step to install the required dependencies from the requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step to run unit tests
      - name: Run tests
        env:
          PYTHONPATH: ./src
        run: python -m unittest discover -s src/test -v

      # Step to run the main script if tests pass
      - name: Update links
        env:
          FOOD_MENU_SHEET_PUBLIC_URL: ${{ secrets.FOOD_MENU_SHEET_PUBLIC_URL }}
          DUB_API_KEY: ${{ secrets.DUB_API_KEY }}
          BREAKFAST_LINK_ID: ${{ secrets.BREAKFAST_LINK_ID }}
          LUNCH_LINK_ID: ${{ secrets.LUNCH_LINK_ID }}
          DINNER_LINK_ID: ${{ secrets.DINNER_LINK_ID }}
          PYTHONPATH: ./src
        run: python src/main.py
